// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imcuuziargvldmdaqkvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltY3V1emlhcmd2bGRtZGFxa3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0Nzc4MjksImV4cCI6MjA1NTA1MzgyOX0.9DYV_Ksry7juYmvlac2UEJj7axon4zWya-wDLQi3drw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});